FS-part4-1team-FitMate/FitMate-BE

prisma/schema.prisma
=> Refactor: prisma schema refactor

package.json
=> chore: update dev script in package.json

prisma/schema.prisma
=> refactor: shcema user profile name nickname

src/app.module.ts, src/main.ts, src/user/type/user.dto.ts, src/user/type/user.type.ts
- close #이슈번호
.env 파일
```
DATABASE_URL="postgresql://postgres:password@localhost:5432/fitmate_dev?schema=public"
PORT=3000
```
=> [소재희] fix: rename name field to nickname in user dto

src/main.ts
- close #이슈번호
.env 파일에 다음 내용을 추가해 주세요
```
CORS_ORIGIN="http://localhost:3001"
```
=> [소재희] chore: configure CORS

https/lesson.http, src/lesson/dto/lesson.dto.ts, src/lesson/interface/lesson-service.interface.ts, src/lesson/lesson.controller.ts, src/lesson/lesson.repository.ts, src/lesson/lesson.service.ts, src/main.ts
- close #22 이슈번호
* 요청 및 응답에 대한 내용은 저희 팀 노션 API 명세서를 참조해 주세요
* Rest Client로 실행할 수 있는 코드가 /https/lesson.http 에 있습니다.
=> feat: implement lesson list, detail, create, and cancel APIs

src/auth/auth.controller.ts, src/auth/auth.module.ts, src/auth/auth.service.ts, src/auth/guard/access-token.guard.ts
=> 42 feat include profile in auth and refine accesstokenguard

package-lock.json, package.json, src/auth/auth.controller.ts, src/auth/auth.module.ts, src/auth/auth.service.ts, src/exception/auth-exception-message.ts, src/user/user.repository.ts, src/utils/map-to-role.ts
=> feat: google login

src/trainer/trainer.repository.ts
- close #51 
-[ ] 다른 팀원에게 알릴 내용이 있으면 작성해주세요.
=> refactor: add experience sort

src/auth/auth.controller.ts, src/auth/auth.service.ts, src/auth/interface/auth.service.interface.ts, src/user/interface/user.repository.interface.ts, src/user/user.repository.ts
=> 56 resolve include redirecturl in social login response

src/auth/auth.controller.ts
=> refactor: redirect

docs/test.txt
=> docs: slack test

src/trainer/interface/trainer.service.interface.ts, src/trainer/trainer.controller.ts, src/trainer/trainer.service.ts
=> feat: add my favorite trainer list

prisma/mock/lesson_quote.mock.ts, src/quote/quote.repository.ts, src/quote/quote.service.ts
- close #81 이슈번호
* 프론트엔드 요청사항 반영이라 일단 As is 상황에서 구현했고, 향후 리팩토링 예정입니다.
=> feat: include lessons infomation in quotes list response

prisma/mock/review.mock.ts, prisma/seed.ts, src/review/dto/review.dto.ts, src/review/interface/review.repository.interface.ts, src/review/interface/review.service.interface.ts, src/review/review.controller.ts, src/review/review.repository.ts, src/review/review.service.ts, src/review/type/review.type.ts
=> feat: review list

src/review/dto/review.dto.ts, src/review/interface/review.repository.interface.ts, src/review/review.http, src/review/review.module.ts, src/review/review.repository.ts, src/review/review.service.ts
=> refactor: code refactoring

.github/workflows/deploy.yml
=> Create  deploy.yml

.github/workflows/deploy.yml, src/main.ts
=> dev to main

package-lock.json, package.json, prisma/mock/direct_quote_request.mock.ts, prisma/mock/lesson_quote.mock.ts, prisma/mock/lesson_request.mock.ts, prisma/mock/review.mock.ts, src/exception/lesson-exception-message.ts, src/lesson/dto/lesson.dto.ts, src/lesson/lesson.controller.ts, src/lesson/lesson.service.ts
=> Feat: set quote end date automatically on lesson request

src/auth/auth.module.ts, src/exception/quote-exception-message.ts, src/quote/quote.module.ts, src/quote/quote.service.ts
=> feat: check profile registration for creating quote

package-lock.json, src/auth/auth.controller.ts, src/auth/auth.service.ts, src/auth/interface/auth.service.interface.ts, src/auth/strategy/kakao.strategy.ts, src/auth/strategy/naver.strategy.ts, src/utils/get-env.ts
=> feat: Redirect to SNS login page with error message on login failure & feat: Add error handling for missing env variables

prisma/mock/favorite_trainers.mock.ts, prisma/seed.ts, src/review/review.repository.ts, src/review/type/review.type.ts, src/trainer/interface/trainer.service.interface.ts, src/trainer/trainer.controller.ts, src/trainer/trainer.module.ts, src/trainer/trainer.repository.ts, src/trainer/trainer.service.ts
=> refactor: review rating and favorite trainer logic modified

src/chat/chat.gateway.ts
=> refactor: sockeet references modified

src/quote/interface/quote-repository.interface.ts, src/quote/quote.repository.ts, src/quote/type/quote.type.ts
=> feat: update reviewable quote response

README.md
=> feat: readme write complete

prisma/mock/lesson_quote.mock.ts, prisma/mock/review.mock.ts
- close #163 
- [] 세부 작업 사항들을 작성해주세요.
- [] 세부 작업 사항들을 작성해주세요.
=> fix: mock data modified

prisma/mock/review.mock.ts
- close #이슈번호
- [] 세부 작업 사항들을 작성해주세요.
- [] 세부 작업 사항들을 작성해주세요.
=> fix:review mock data uuid modified

src/notification/interface/notification-service.interface.ts, src/notification/notification.service.ts
- close #이슈번호
```
async createChatNotification(userId: string, message: string): Promise<NotificationResponse> {
const notification = await this.notificationRepository.createNotification({
userId,
type: 'CHAT_MESSAGE',
message,
});
return notification;
}
```
=> feat: add createChatNotification to notification service

src/trainer/trainer.service.ts
- close #이슈번호
- [] 강사님 찾기에 이름 검색 추가
- 
-[x] 다른 팀원에게 알릴 내용이 있으면 작성해주세요.
FE의 긴급요청으로 제가 트레이너 검색 작업 추가했습니다.
=> feat add name contdition to trainer search

src/configs/jwt.config.ts
- close #이슈번호
- [] acessToken 만료 1day로 변경
=> chore: update accessToken expired time

src/chat/chat.gateway.ts, src/chat/chat.service.ts, src/chat/dto/chat.dto.ts
=> sender id 가지고 오는 방식으로 수정

src/trainer/trainer.module.ts, src/trainer/trainer.repository.ts, src/trainer/trainer.service.ts
- close #177 
- [] 세부 작업 사항들을 작성해주세요.
- [] 세부 작업 사항들을 작성해주세요.
=> refactor: trainer profile image preSignedURL
